;;; emacs-ansi-color.el --- matugen-generated ANSI colour theme  -*- lexical-binding: t; -*-
;; Generated by matugen — do not edit manually.
;; Source template: ~/.config/matugen/templates/emacs-ansi-color.el
;; Output path:     ~/.config/emacs/themes/ansi-color.el
;;
;; Load from your init.el:
;;   (load (expand-file-name "themes/ansi-color.el" user-emacs-directory) :noerror)

;;; Code:

(custom-set-faces
 ;; ── Normal colours ──────────────────────────────────────────────────────────
 '(ansi-color-black          ((t (:foreground "{{dank16.color0.default.hex}}"  :background "{{dank16.color0.default.hex}}"))))
 '(ansi-color-red            ((t (:foreground "{{dank16.color1.default.hex}}"  :background "{{dank16.color1.default.hex}}"))))
 '(ansi-color-green          ((t (:foreground "{{dank16.color2.default.hex}}"  :background "{{dank16.color2.default.hex}}"))))
 '(ansi-color-yellow         ((t (:foreground "{{dank16.color3.default.hex}}"  :background "{{dank16.color3.default.hex}}"))))
 '(ansi-color-blue           ((t (:foreground "{{dank16.color4.default.hex}}"  :background "{{dank16.color4.default.hex}}"))))
 '(ansi-color-magenta        ((t (:foreground "{{dank16.color5.default.hex}}"  :background "{{dank16.color5.default.hex}}"))))
 '(ansi-color-cyan           ((t (:foreground "{{dank16.color6.default.hex}}"  :background "{{dank16.color6.default.hex}}"))))
 '(ansi-color-white          ((t (:foreground "{{dank16.color7.default.hex}}"  :background "{{dank16.color7.default.hex}}"))))

 ;; ── Bright colours ──────────────────────────────────────────────────────────
 '(ansi-color-bright-black   ((t (:foreground "{{dank16.color8.default.hex}}"  :background "{{dank16.color8.default.hex}}"))))
 '(ansi-color-bright-red     ((t (:foreground "{{dank16.color9.default.hex}}"  :background "{{dank16.color9.default.hex}}"))))
 '(ansi-color-bright-green   ((t (:foreground "{{dank16.color10.default.hex}}" :background "{{dank16.color10.default.hex}}"))))
 '(ansi-color-bright-yellow  ((t (:foreground "{{dank16.color11.default.hex}}" :background "{{dank16.color11.default.hex}}"))))
 '(ansi-color-bright-blue    ((t (:foreground "{{dank16.color12.default.hex}}" :background "{{dank16.color12.default.hex}}"))))
 '(ansi-color-bright-magenta ((t (:foreground "{{dank16.color13.default.hex}}" :background "{{dank16.color13.default.hex}}"))))
 '(ansi-color-bright-cyan    ((t (:foreground "{{dank16.color14.default.hex}}" :background "{{dank16.color14.default.hex}}"))))
 '(ansi-color-bright-white   ((t (:foreground "{{dank16.color15.default.hex}}" :background "{{dank16.color15.default.hex}}"))))

 ;; ── term-mode faces (M-x term, M-x shell) ───────────────────────────────────
 '(term-color-black   ((t (:foreground "{{dank16.color0.default.hex}}"  :background "{{dank16.color0.default.hex}}"))))
 '(term-color-red     ((t (:foreground "{{dank16.color1.default.hex}}"  :background "{{dank16.color1.default.hex}}"))))
 '(term-color-green   ((t (:foreground "{{dank16.color2.default.hex}}"  :background "{{dank16.color2.default.hex}}"))))
 '(term-color-yellow  ((t (:foreground "{{dank16.color3.default.hex}}"  :background "{{dank16.color3.default.hex}}"))))
 '(term-color-blue    ((t (:foreground "{{dank16.color4.default.hex}}"  :background "{{dank16.color4.default.hex}}"))))
 '(term-color-magenta ((t (:foreground "{{dank16.color5.default.hex}}"  :background "{{dank16.color5.default.hex}}"))))
 '(term-color-cyan    ((t (:foreground "{{dank16.color6.default.hex}}"  :background "{{dank16.color6.default.hex}}"))))
 '(term-color-white   ((t (:foreground "{{dank16.color7.default.hex}}"  :background "{{dank16.color7.default.hex}}"))))
 '(term-color-bright-black   ((t (:foreground "{{dank16.color8.default.hex}}"  :background "{{dank16.color8.default.hex}}"))))
 '(term-color-bright-red     ((t (:foreground "{{dank16.color9.default.hex}}"  :background "{{dank16.color9.default.hex}}"))))
 '(term-color-bright-green   ((t (:foreground "{{dank16.color10.default.hex}}" :background "{{dank16.color10.default.hex}}"))))
 '(term-color-bright-yellow  ((t (:foreground "{{dank16.color11.default.hex}}" :background "{{dank16.color11.default.hex}}"))))
 '(term-color-bright-blue    ((t (:foreground "{{dank16.color12.default.hex}}" :background "{{dank16.color12.default.hex}}"))))
 '(term-color-bright-magenta ((t (:foreground "{{dank16.color13.default.hex}}" :background "{{dank16.color13.default.hex}}"))))
 '(term-color-bright-cyan    ((t (:foreground "{{dank16.color14.default.hex}}" :background "{{dank16.color14.default.hex}}"))))
 '(term-color-bright-white   ((t (:foreground "{{dank16.color15.default.hex}}" :background "{{dank16.color15.default.hex}}"))))
 )

;; Sync vectors so comint, xterm-color, eat, vterm etc. read the same palette.
(setq ansi-color-names-vector
      ["{{dank16.color0.default.hex}}"
       "{{dank16.color1.default.hex}}"
       "{{dank16.color2.default.hex}}"
       "{{dank16.color3.default.hex}}"
       "{{dank16.color4.default.hex}}"
       "{{dank16.color5.default.hex}}"
       "{{dank16.color6.default.hex}}"
       "{{dank16.color7.default.hex}}"])

(setq ansi-color-bright-colors-vector
      ["{{dank16.color8.default.hex}}"
       "{{dank16.color9.default.hex}}"
       "{{dank16.color10.default.hex}}"
       "{{dank16.color11.default.hex}}"
       "{{dank16.color12.default.hex}}"
       "{{dank16.color13.default.hex}}"
       "{{dank16.color14.default.hex}}"
       "{{dank16.color15.default.hex}}"])

(provide 'ansi-color-matugen)
;;; emacs-ansi-color.el ends here
