;;; emacs-diredfl.el --- matugen-generated diredfl colour theme  -*- lexical-binding: t; -*-
;; Generated by matugen — do not edit manually.
;; Source template: ~/.config/matugen/templates/emacs-diredfl.el
;; Output path:     ~/.config/emacs/themes/diredfl.el
;;
;; Load from your init.el (after diredfl is loaded):
;;   (load (expand-file-name "themes/diredfl.el" user-emacs-directory) :noerror)

;;; Code:

(custom-set-faces

 ;; ── File names ──────────────────────────────────────────────────────────────

 ;; Regular file base name (no suffix)
 ;; → on_surface: the normal readable text colour
 '(diredfl-file-name
   ((t (:foreground "{{colors.on_surface.default.hex}}"))))

 ;; File suffix / extension  (.el, .py …)
 ;; → color6 (cyan): secondary accent, visually distinct but calm
 '(diredfl-file-suffix
   ((t (:foreground "{{dank16.color6.default.hex}}"))))

 ;; Compressed file name (.tar, .zip …)
 ;; → color3 (yellow): draws attention without alarm
 '(diredfl-compressed-file-name
   ((t (:foreground "{{dank16.color3.default.hex}}"))))

 ;; Compressed file suffix (.zip, .gz …)
 ;; → color3 bright: same family, slightly stronger
 '(diredfl-compressed-file-suffix
   ((t (:foreground "{{dank16.color11.default.hex}}"))))

 ;; Ignored / omitted file names
 ;; → outline variant: dim, de-emphasised
 '(diredfl-ignored-file-name
   ((t (:foreground "{{colors.outline.default.hex}}"))))

 ;; Executable (*) tag appended to filename
 ;; → color1 (red): clear "this runs" signal
 '(diredfl-executable-tag
   ((t (:foreground "{{dank16.color1.default.hex}}" :bold t))))

 ;; ── Directories & symlinks ───────────────────────────────────────────────────

 ;; Directory name (the coloured part of a dir entry)
 ;; → color4 (blue) fg on surface-variant bg
 '(diredfl-dir-name
   ((t (:foreground "{{dank16.color4.default.hex}}" :bold t))))

 ;; Directory heading (e.g. "/home/nox/projects:")
 ;; → primary + surface bg: section header treatment
 '(diredfl-dir-heading
   ((t (:foreground "{{colors.primary.default.hex}}"
                    :bold t :underline t))))

 ;; Symbolic links
 ;; → color14 (bright cyan): links feel "connected"
 '(diredfl-symlink
   ((t (:foreground "{{dank16.color14.default.hex}}"))))

 ;; ── Flag / mark lines ────────────────────────────────────────────────────────

 ;; Entire line that is flagged or marked (background wash)
 ;; → secondary_container: gentle highlight behind marked lines
 '(diredfl-flag-mark-line
   ((t (:foreground "{{colors.secondary_container.default.hex}}"))))

 ;; The flag/mark character itself (* % …)
 ;; → color5 (magenta): pops against the washed background
 '(diredfl-flag-mark
   ((t (:foreground "{{dank16.color5.default.hex}}" :bold t))))

 ;; Entire deletion-flagged line
 ;; → error_container bg: unmistakable danger
 '(diredfl-deletion-file-name
   ((t (:foreground "{{colors.on_error_container.default.hex}}"
                    :background "{{colors.error_container.default.hex}}"))))

 ;; The D deletion flag character
 ;; → color9 (bright red) on color1 (red): maximum visibility
 '(diredfl-deletion
   ((t (:foreground "{{dank16.color15.default.hex}}"
                    :background "{{dank16.color1.default.hex}}"
                    :bold t))))

 ;; ── Metadata columns ─────────────────────────────────────────────────────────

 ;; Date / time column
 ;; → color12 (bright blue): calm, informational
 '(diredfl-date-time
   ((t (:foreground "{{dank16.color12.default.hex}}"))))

 ;; Numeric fields: inode, hard-link count, file size
 ;; → color11 (bright yellow): numbers stand out from text
 '(diredfl-number
   ((t (:foreground "{{dank16.color11.default.hex}}"))))

 ;; ── Permission bits ──────────────────────────────────────────────────────────

 ;; d (directory privilege indicator)
 ;; → same as dir-name for consistency
 '(diredfl-dir-priv
   ((t (:foreground "{{dank16.color4.default.hex}}"))))

 ;; l (symlink type indicator)
 ;; → same as symlink face
 '(diredfl-link-priv
   ((t (:foreground "{{dank16.color14.default.hex}}"))))

 ;; r (read bit)
 ;; → color2 (green): "allowed to see"
 '(diredfl-read-priv
   ((t (:foreground "{{dank16.color2.default.hex}}"))))

 ;; w (write bit)
 ;; → color3 (yellow): "allowed to change"
 '(diredfl-write-priv
   ((t (:foreground "{{dank16.color3.default.hex}}"))))

 ;; x (execute bit)
 ;; → color1 (red): "allowed to run"
 '(diredfl-exec-priv
   ((t (:foreground "{{dank16.color1.default.hex}}"))))

 ;; - (no permission)
 ;; → outline: visually present but clearly absent
 '(diredfl-no-priv
   ((t (:foreground "{{colors.outline.default.hex}}"))))

 ;; l/s/S/t/T (sticky, setuid, setgid …)
 ;; → color13 (bright magenta): unusual, worth noticing
 '(diredfl-other-priv
   ((t (:foreground "{{dank16.color13.default.hex}}"))))

 ;; b/c/s/m/p/S (block, char, socket, pipe …)
 ;; → color5 (magenta) bold: rare device types
 '(diredfl-rare-priv
   ((t (:foreground "{{dank16.color5.default.hex}}" :bold t))))

 ;; ── Bookmark integration (requires bookmark+) ────────────────────────────────

 ;; Autofile bookmark (untagged)
 ;; → tertiary_container bg: subtle bookmark indicator
 '(diredfl-autofile-name
   ((t (:background "{{colors.tertiary_container.default.hex}}"))))

 ;; Autofile bookmark (tagged)
 ;; → tertiary bg: tagged = more notable than untagged
 '(diredfl-tagged-autofile-name
   ((t (:background "{{colors.tertiary.default.hex}}"
                    :foreground "{{colors.on_tertiary.default.hex}}"))))
 )

(provide 'diredfl-matugen)
;;; emacs-diredfl.el ends here
