{
  imports = [
    ./networking.nix
    ./locale.nix
    ./fonts.nix
    ./audio.nix
    ./audio-devices.nix
    ./desktop
    ./ssh.nix
    ./security.nix
    ./xremap.nix
    ./bluetooth.nix
    ./monitor.nix
    ./nvidia.nix
    ./nix-ld.nix
    ./tailscale.nix
    ./environment.nix
    ./hardware-tuning.nix
    ./services.nix
    ./users.nix
    ./wireshark.nix
    ./boot.nix
    ./secrets.nix
    ./virtualisation.nix
    ./platformio.nix
  ];
}
